# Generated by Django 3.1.4 on 2020-12-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='imege',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='imege',
            new_name='image',
        ),
    ]
