# Generated by Django 3.1.4 on 2020-12-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testmodel',
        ),
    ]
