# Generated by Django 3.1.4 on 2021-01-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_order_buying_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buying_type',
        ),
    ]
